//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int pid { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string descr { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
